---
title: "Median WTP calculation"
format: html
output-file: index.html
fig-dpi: 600
webr: 
  show-startup-message: true
  packages: ['boot']
  autoload-packages: true
filters:
  - webr
---

This page contains code to simulate data for a WTP experiment and calculate the median WTP, including its confidence intervals. Make sure to run the code in order for each code block to work. You can edit the code (e.g., the parameters) on this page directly to see how the changes impact the results.

## Setup

This setup code is run automatically when the page loads. It contains two functions that are used in the code sections below.

```{webr-r}
#| autorun: true
func <- function(x) plogis(-(Xb + b * x), lower.tail = FALSE)

boot_median_wtp <- function(formula, data, indices) {
  d <- data[indices, ]
  fit <- glm(formula, data = d, family = binomial())

  coefs <- coef(fit)
  b <- coefs["price"]
  Xb <- coefs["(Intercept)"]

  return(Xb / b * -1)
}
```

## Simulate data

Here you can set the parameters of the simulation:

- `N`: The sample size
- `prices`: The set of prices used in the study. A respondent will see one of these prices and are asked whether they accept or reject a price increase of this amount
- `wtp_mean`: The mean of the population's willingness to pay.
- `wtp_sd`: The standard devation of the population's willingness to pay.

A data frame is created with `N` rows and two columns. The first column contains a randomly selected price increase (from `prices`) for each participant. The second column, added later, indicates whether the respondent accepts (1) or rejects (0) the price increase. This is done by randomly sampling a value from the WTP normal distribution (determine by `wtp_mean` and `wtp_sd`); if the sampled value is larger than the price, the respondent accepts, otherwise they reject the price increase.

```{webr-r}
# Parameters
N <- 1000
prices <- c(0.10, 0.25, 0.50, 1, 2, 5)
wtp_mean <- 0.50
wtp_sd <- 1

# Create the data
data <- data.frame(
  price = sample(prices, size = N, replace = TRUE)
)

data$accept <- ifelse(
  rnorm(N, mean = wtp_mean, sd = wtp_sd) >= data$price,
  1, 0
)

head(data)
```

## Analyze data

### Run the model

The way to analyze this data is by running a logistic regression with whether or not the respondent accepts the price increase as the outcome and the price increase as the predictor.

```{webr-r}
model <- glm(accept ~ price, data = data, family = binomial())
summary(model)
```

### Calculate median WTP

The median WTP is calculated dividing the coefficient of the intercept by the coefficient of the price; the sign is flipped to make it a positive result.

```{webr-r}
coefs <- coef(model)
b <- coefs["price"]
Xb <- coefs["(Intercept)"]

Xb / b * -1 # Median WTP
```

### Calculate median WTP confidence interval

Confidence intervals are calculated by bootstrapping the previous step 1000 times.

```{webr-r}
results <- boot(
  formula = accept ~ price,
  data = data,
  statistic = boot_median_wtp,
  R = 1000
)

boot.ci(results, conf = 0.95, type = "bca")
```